### PR TITLE
Update WeatherStream.cpp

### PR DESCRIPTION
**Pull request by RobBryce**
Fix on return value.

### CODE REVIEW

**Comment by spydmobile** [comment]
@RobBryce there is no issue connected to this, so it would be rejected. 
connect an issue(s) please.

**Review by spydmobile — CHANGES_REQUESTED** [review]
Please create/connect an issue describing the problem please. Even a quick hotfix needs a target. Remember the issue title will be reflected in the change logs later.....

**Comment by BadgerOnABike** [comment]
> Please create/connect an issue describing the problem please. Even a quick hotfix needs a target. Remember the issue title will be reflected in the change logs later.....

I'm pretty sure PR's are a part of that change logging system.

**Comment by spydmobile** [comment]
> > Please create/connect an issue describing the problem please. Even a quick hotfix needs a target. Remember the issue title will be reflected in the change logs later.....
> 
> I'm pretty sure PR's are a part of that change logging system.

LOL yes, but only if you fix an issue, if you just create a pull request without an issue, it wont, and our SOP is one bug/fr = one issue, and that issue is encapulated by fixing it on a PR or by at minimum linking it to PR. If you are sure @BadgerOnABike show me which issue this pertains to BEFORE I approve it ;-)

**Comment by RobBryce** [comment]
https://github.com/WISE-Developers/Project_issues/issues/194 is the issue for this pull request.

**Comment by BadgerOnABike** [comment]
Issue is in project issues until I get the organizational health documents established.

**Review by spydmobile — APPROVED** [review]
super thanks!

**Pull request merged**
